version: '2'

services:
  webknossos-datastore:
    image: scalableminds/webknossos-datastore:$DOCKER_TAG
    ports:
      - "9090:9090"

  sbt:
    image: scalableminds/sbt:$SBT_VERSION_TAG
    volumes:
      - ".:/project"
      - "~/.m2:/root/.m2"
      - "~/.ivy2:/root/.ivy2"
      - "~/.sbt:/root/.sbt"

  dev:
    extends:
      service: sbt
    ports:
      - "9090:9090"
      - "5005:5005"
    command: >
      bash -c
      "sbt -v -d -jvm-debug 5005 \"run
      -Djava.net.preferIPv4Stack=true
      -Dhttp.address=0.0.0.0
      -Dhttp.port=$${PORT}
      \""
    environment:
      - PORT=9090
    stdin_open: true

  prod:
    extends:
      service: dev
    command: >
      bash -c
      "sbt -v -d -jvm-debug 5005 \"testProd
      -Djava.net.preferIPv4Stack=true
      -Dhttp.address=0.0.0.0
      -Dhttp.port=$${PORT}
      \""
